# #####################################################################
# Automatically generated by qmake (2.01a) ?? ?? 14 16:15:17 2009
# #####################################################################
TEMPLATE = lib
DESTDIR = ../../lib            
TARGET =
CONFIG += qt debug
LIBS += -L../../lib/ -lmatrix
MOC_DIR = unixcompile
OBJECTS_DIR = unixcompile
UI_HEADERS_DIR = unixcompile
UI_SOURCES_DIR = unixcompile

# Input
HEADERS += scatterdata.h
SOURCES += scatterdata.cpp
