######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 21 21:49:43 2009
######################################################################
TEMPLATE = lib
DESTDIR = ../../lib            
DEPENDPATH += .
INCLUDEPATH += .                
CONFIG += qt debug

MOC_DIR = unixcompile
OBJECTS_DIR = unixcompile
UI_HEADERS_DIR = unixcompile
UI_SOURCES_DIR = unixcompile

# Input
HEADERS += colormap.h
SOURCES += colormap.cpp
