# #####################################################################
# Automatically generated by qmake (2.01a) ?? ??? 12 15:02:09 2008
# #####################################################################
TEMPLATE = lib
DESTDIR = ../../lib            
DEPENDPATH += .
INCLUDEPATH += .                
CONFIG += qt debug

# Input
HEADERS += 2DMemAllocator.h \
    matrix.h
SOURCES += 2DMemAllocator.cpp \
#main.cpp\
    matrix.cpp
RESOURCES += matrix.qrc
