######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 15 11:56:46 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
